name: Code quality
on:
  pull_request:
jobs:
  quality:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Run code quality
        uses: ./.github/actions/code-quality
